// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrderCookDeliver.Data;

namespace OrderCookDeliver.Migrations
{
    [DbContext(typeof(OrderCookDeliverContext))]
    [Migration("20191121043448_Calendar")]
    partial class Calendar
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OrderCookDeliver.Models.Calendar", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("calPerServg")
                        .HasColumnType("float");

                    b.Property<double>("cholesterol")
                        .HasColumnType("float");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("dietaryFiber")
                        .HasColumnType("float");

                    b.Property<string>("ingredient_1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ingredient_10")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ingredient_11")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ingredient_12")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ingredient_13")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ingredient_14")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ingredient_15")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ingredient_16")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ingredient_17")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ingredient_2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ingredient_3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ingredient_4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ingredient_5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ingredient_6")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ingredient_7")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ingredient_8")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ingredient_9")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mealId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mealName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("monoUnsatFat")
                        .HasColumnType("float");

                    b.Property<double>("omega_3")
                        .HasColumnType("float");

                    b.Property<double>("omega_6")
                        .HasColumnType("float");

                    b.Property<double>("polyUnsatFat")
                        .HasColumnType("float");

                    b.Property<int>("preparationTime")
                        .HasColumnType("int");

                    b.Property<double>("pricePerServg")
                        .HasColumnType("float");

                    b.Property<string>("procedure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("protein")
                        .HasColumnType("float");

                    b.Property<double>("saturatedFat")
                        .HasColumnType("float");

                    b.Property<double>("sugar")
                        .HasColumnType("float");

                    b.Property<double>("totalCarb")
                        .HasColumnType("float");

                    b.Property<double>("totalFat")
                        .HasColumnType("float");

                    b.Property<double>("transFat")
                        .HasColumnType("float");

                    b.HasKey("ID");

                    b.ToTable("Calendar");
                });

            modelBuilder.Entity("OrderCookDeliver.Models.Cart", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Meal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Serving")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Cart");
                });
#pragma warning restore 612, 618
        }
    }
}
